In [2]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant([[1,2], [3,4]])

In [3]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [4]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

## Matrix multiplication with tensorflow

In [44]:
a = tf.constant([[23,12,34], [12, 0, 1], [54, 98, 32], [0,0,0], [4,4,4]])

b = tf.constant([[3,3,3,3,3], [2,2,2,2,2], [5,5,5,5,5]])

In [6]:
tf.matmul(a,b)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[263, 263, 263, 263, 263],
       [ 41,  41,  41,  41,  41],
       [518, 518, 518, 518, 518],
       [  0,   0,   0,   0,   0],
       [ 40,  40,  40,  40,  40]])>

In [25]:
a = tf.constant([0,1,3,4,14,18,20,23,13,59,99,0], shape=[3,4])

In [26]:
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  3,  4],
       [14, 18, 20, 23],
       [13, 59, 99,  0]])>

In [31]:
A = tf.constant([3,7,1,9], shape=[2,2])

In [32]:
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 7],
       [1, 9]])>

In [34]:
V = tf.constant([5,2], shape=[2,1])

V

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [2]])>

In [35]:
tf.matmul(A,V)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[29],
       [23]])>

## Element-wise multiplication

In [46]:
tf.math.multiply(A, V)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 35],
       [ 2, 18]])>

In [60]:
a = tf.constant([2,3,5,6], shape=[4,1])

In [61]:
a

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [3],
       [5],
       [6]])>

In [54]:
b = tf.constant([3,2,4,5,8,12,1,7], shape=[4,2])

In [55]:
b

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 4,  5],
       [ 8, 12],
       [ 1,  7]])>

In [62]:
tf.math.multiply(a,b)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 6,  4],
       [12, 15],
       [40, 60],
       [ 6, 42]])>

In [ ]:
2,2
2,1

In [63]:
tf.multiply(a,b)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 6,  4],
       [12, 15],
       [40, 60],
       [ 6, 42]])>

In [64]:
tf.eye(3,4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [67]:
tf.eye(3,4,dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])>

In [70]:
A = tf.constant([23,12, 45,61,9,0,1,5,6,8,9,12,43,71,42,17,82,39,8,20], shape=[5,4])

B = tf.constant([12,34,86,1,8,0,23,74,52,13,49,33], shape=[4,3])

print(A, "\n\n", B)

tf.Tensor(
[[23 12 45 61]
 [ 9  0  1  5]
 [ 6  8  9 12]
 [43 71 42 17]
 [82 39  8 20]], shape=(5, 4), dtype=int32) 

 tf.Tensor(
[[12 34 86]
 [ 1  8  0]
 [23 74 52]
 [13 49 33]], shape=(4, 3), dtype=int32)


In [71]:
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[2116, 7197, 6331],
       [ 196,  625,  991],
       [ 443, 1522, 1380],
       [1774, 5971, 6443],
       [1467, 4672, 8128]])>

In [73]:
tf.tensordot(A, B, axes=1)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[2116, 7197, 6331],
       [ 196,  625,  991],
       [ 443, 1522, 1380],
       [1774, 5971, 6443],
       [1467, 4672, 8128]])>

## In identity matrix, multiply with anything and we will get the same result

In [87]:
A = tf.constant([9,32,0,12,54,65,12,37,81,11,12,77], shape=[3,4])

B = tf.eye(4,4, dtype=tf.int32)


In [81]:
A

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9, 32,  0, 12],
       [54, 65, 12, 37],
       [81, 11, 12, 77]])>

In [88]:
B

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])>

In [89]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9, 32,  0, 12],
       [54, 65, 12, 37],
       [81, 11, 12, 77]])>

In [84]:
B = tf.eye(3,4,dtype=tf.int32)

In [85]:
B

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])>

In [90]:
A = tf.constant([32,83, 5, 17, 23, 10, 75, 39, 52], shape=[3,3])

A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[32, 83,  5],
       [17, 23, 10],
       [75, 39, 52]])>

In [92]:
ident = tf.eye(3,3, dtype=tf.int32)
ident

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>

In [93]:
tf.matmul(A,ident)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[32, 83,  5],
       [17, 23, 10],
       [75, 39, 52]])>

In [104]:
a = tf.random.normal(shape=(2,2))

b = tf.random.normal(shape=(2,2))

print(a, '\n\n', b)

with tf.GradientTape() as tape:
    tape.watch(a)
    tape.watch(b)
    c = tf.sqrt(tf.square(a) + tf.square(b))

print('\n\n', c)

# dc_da = tape.gradient(c, a)
# print('\n\n' ,dc_da)

dc_db = tape.gradient(c, b)
print('\n\n', dc_db)

tf.Tensor(
[[-0.57680047 -0.78196603]
 [-0.27804393  1.1757021 ]], shape=(2, 2), dtype=float32) 

 tf.Tensor(
[[1.1133611  0.39968735]
 [1.1374512  0.16589966]], shape=(2, 2), dtype=float32)


 tf.Tensor(
[[1.2539027 0.8781918]
 [1.1709414 1.1873492]], shape=(2, 2), dtype=float32)


 tf.Tensor(
[[0.88791674 0.45512533]
 [0.97139895 0.13972272]], shape=(2, 2), dtype=float32)


In [99]:
# We know that dc/da = a/sqrt(a^2+b^2)

result = a/tf.sqrt(tf.square(a)+tf.square(b))

In [100]:
result

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.4838658 , -0.98244715],
       [ 0.9978928 , -0.9999999 ]], dtype=float32)>

In [109]:
a = tf.Variable(a)
b = tf.Variable(b)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    # dc_da = tape.gradient(c, a)
    # print(dc_da)
    d_db=tape.gradient(c, b)
    print(dc_db)

tf.Tensor(
[[0.88791674 0.45512533]
 [0.97139895 0.13972272]], shape=(2, 2), dtype=float32)


In [110]:
 a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.57680047, -0.78196603],
       [-0.27804393,  1.1757021 ]], dtype=float32)>

In [112]:
# we will see here double differentiation

with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        c = tf.sqrt(tf.square(a) +tf.square(b))
        dc_da = inner_tape.gradient(c, a)
    d2c_da2 = outer_tape.gradient(dc_da, a)
    print(d2c_da2)

tf.Tensor(
[[0.6287539  0.23587006]
 [0.80586094 0.01644206]], shape=(2, 2), dtype=float32)


In [114]:
tf.tanh(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9640276>

In [125]:
def tanh(x):
    return tf.tanh(x)

def get_gradient(x, activation_function):
    with tf.GradientTape() as gt:
        y = activation_function(x)

        gradient = gt.gradient(y, x)

    return gradient

x = tf.Variable(-4.1)
gradient = get_gradient(x, tanh)

    
print(f"Gradient of tanh(x) with x = {x.numpy()} is: {gradient}")

Gradient of tanh(x) with x = -4.099999904632568 is: 0.0010978544596582651


## End-to-End Example for TensorFlow - with Linear Regression

In [3]:
input_dims = 2
output_dims = 1
learning_rate = 0.01 # Subject to change

# This is our weight matrix:

w = tf.Variable(tf.random.uniform(shape=(input_dims, output_dims)))     # Paramters equal to theta

# This's our bias vector:

b = tf.Variable(tf.zeros(shape=(output_dims,)))   # Intercept

# Define Hypothesis:

def compute_predictions(features):
    return tf.matmul(features, w) + b

def compute_loss(target, predictions):   # Define MSE
    return tf.reduce_mean(tf.square(target-predictions))

def train(x, y):      # Training and udating through GD updates
    with tf.GradientTape() as tape:
        predictions = compute_predictions(x)   # y_prediction or y_hat
        loss = compute_loss(y, predictions)    # Loss calculation
        dloss_dw, dloss_db = tape.gradient(loss, [w,b])    # Gradient w.r.t. w and b
    w.assign_sub(learning_rate*dloss_dw)   # Reassign weights

    b.assign_sub(leanirng_rate*dloss_db)   # Reassign bias
    return loss


### Homework

#### To generate and utilize the above code to run a simple linear regression

## Tolerance = 1e-3

#### Write a function for predict()
#### Write a R2 and adj R2 score metric
#### Write a loop and stop training when tolerance condition is met

In [ ]:
x = tf.random. 