In [1]:
import numpy as np
import tensorflow as tf

In [14]:
# pip install "tensorflow<2.11"

In [6]:
# pip install numpy==1.21

In [7]:
np.__version__

'1.21.0'

In [ ]:
# pip uninstall tensorflow

In [15]:
print("Is TensorFlow built with CUDA:", tf.test.is_built_with_cuda())

Is TensorFlow built with CUDA: True


In [16]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [17]:
gpus = tf.config.list_physical_devices('GPU')
print("Available GPUs: ", gpus)

for gpu in gpus:
    details = tf.config.experimental.get_device_details(gpu)
    print(f"Device Name: {details.get('device_name')}")

Available GPUs:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Device Name: NVIDIA GeForce RTX 2070


In [18]:
tf.__version__

'2.10.1'

In [12]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [13]:
gpus = tf.config.experimental.list_physical_devices('GPU')

# Check if GPUs are available
if gpus:
    for gpu in gpus:
        gpu_name = tf.config.experimental.get_device_details(gpu).get('device_name')
        print(f"GPU Name: {gpu_name}")
else:
    print("No GPU available")

GPU Name: NVIDIA GeForce RTX 2070


In [14]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [15]:
[i for i in tf.config.list_physical_devices()]

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [44]:
!nvidia-smi

Tue Aug 13 16:09:27 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.81                 Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   65C    P8              5W /  115W |    6676MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [17]:
!nvidia-smi -L

GPU 0: NVIDIA GeForce RTX 2070 (UUID: GPU-a312207a-f974-2b05-3d75-bcda3f84c528)


In [18]:
a = tf.random.normal(shape=(5, 3))

In [19]:
print(a)

tf.Tensor(
[[-0.18506835 -0.19241688  0.45951548]
 [ 0.23407519 -1.2242646   0.47013912]
 [ 0.86041075  0.3933115   0.43257424]
 [ 1.0048745   0.5622988   1.7013412 ]
 [-0.04866887 -0.1924072   0.871503  ]], shape=(5, 3), dtype=float32)


In [58]:
a.shape

TensorShape([5, 3])

In [59]:
b = tf.random.normal((100, 100, 100, 3))

In [61]:
b.shape

TensorShape([100, 100, 100, 3])

In [62]:
b.ndim

4

In [35]:
# Using CPU at slot 0

with tf.device('/CPU:0'):

    # starting a timer
    start = time.time() 

    # Doing operations on CPU
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.reduce_sum(random_image_cpu)


    # Printing how long it will took for CPU computation:
    end_cpu = time.time() - start
    print(f'Time took for CPU compute: {end_cpu}')


# Using GPU at slot 0

with tf.device('/GPU:0'):

    # Starting a timer

    start = time.time()

    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.reduce_sum(random_image_gpu)

    # Printing how long it took for GPU computation:

    end_gpu =  time.time() - start
    print(f'Time took fro GPU computation: {end_gpu}')
print(f'\nGPU speed-up over CPU: {int(end_cpu/end_gpu)}x')

Time took for CPU compute: 0.027492046356201172
Time took fro GPU computation: 0.0009989738464355469

GPU speed-up over CPU: 27x


In [24]:
tf.debugging.set_log_device_placement(True)

# Run a simple operation to see device placements

a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # Shape (2, 3)
b = tf.constant([[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]])  # Shape (3, 2)

c = tf.matmul(a, b)  # This is valid and will result in a (2, 2) matrix


In [25]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 8766766501046127782
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6272581632
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7030388822160139412
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5"
xla_global_id: 416903419
]


In [26]:
with tf.device('/GPU:0'):

    # Starting a timer
    
    start = time.time()

    random_image_gpu = tf.random.normal((1000, 100, 100, 3))
    net_gpu = tf.reduce_sum(random_image_gpu)

    # Printing how long it took for GPU computation:

    end_gpu =  time.time() - start
    print(f'Time took fro GPU computation: {end_gpu}')

Time took fro GPU computation: 0.00101470947265625


In [42]:
# Generate random numbers with uniform distribution:

a = tf.random.uniform(shape=[5, 4], minval=3, maxval=10)

In [43]:
a

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[7.9528513, 8.746841 , 7.7886467, 9.117251 ],
       [5.737388 , 5.3831954, 3.260429 , 5.5921087],
       [8.013907 , 3.066088 , 5.9464293, 8.504319 ],
       [9.687214 , 9.705658 , 4.2836094, 9.656082 ],
       [3.0962348, 4.5038996, 5.5705786, 9.368619 ]], dtype=float32)>

## Constant in Neural Networks

In [49]:
c = tf.constant(4.0, dtype=tf.float64)

print(c)

tf.Tensor(4.0, shape=(), dtype=float64)


In [50]:
d = np.array([ [1,2,3,], [4,5,6] ])
d.dtype

dtype('int32')

In [51]:
e = tf.constant(d)
e

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [52]:
 e.dtype

tf.int32

In [53]:
d.dtype

dtype('int32')

In [55]:
b = tf.constant([1,2,3])
print(b)
b = tf.expand_dims(b, 1)
b.shape
b

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [69]:
b=tf.expand_dims(b, 0)
b.shape

TensorShape([1, 3, 1])

In [70]:
tf.random.normal(shape=(10, 10), mean=0, stddev=1)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-0.3065732 , -0.7604594 ,  0.91884786,  0.37260583, -0.16597532,
         0.5475341 , -1.0454128 ,  0.9318304 ,  0.20448226, -0.7084755 ],
       [ 1.6374545 ,  0.2779651 , -0.5158457 ,  1.6584864 , -0.211467  ,
        -0.7111922 ,  1.0949564 ,  0.58159256,  1.1573575 ,  0.07399148],
       [-0.0039513 ,  1.6271445 , -0.7359816 ,  1.0269163 ,  0.56987536,
         1.0713485 , -0.7344878 ,  0.86274385,  1.3048829 , -0.4424155 ],
       [ 0.31004488, -0.7477227 ,  0.04706642, -0.3992492 , -1.0916581 ,
         0.94418305,  0.6261594 ,  0.15015008, -0.4363238 ,  0.65599346],
       [-0.86531335, -0.93596864,  0.5927043 ,  1.378649  ,  0.2449582 ,
         0.4547065 , -1.3859239 , -0.72049755,  0.07189207,  0.71066433],
       [-1.3822883 , -0.31660813, -0.30360582, -1.1852727 ,  0.14529382,
         0.39629894, -0.8375262 ,  0.79615533, -1.1971837 , -0.19492777],
       [-1.9050646 ,  1.6744578 , -1.6127363 ,  1.1729386 ,  0.34351

In [72]:
tf.random.uniform(shape=(10, 10), minval=0, maxval=10, dtype='int32')

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[4, 6, 9, 8, 9, 6, 9, 5, 5, 7],
       [7, 6, 5, 0, 9, 5, 0, 5, 5, 4],
       [6, 5, 3, 1, 1, 1, 7, 4, 5, 5],
       [0, 5, 6, 9, 8, 3, 8, 3, 6, 7],
       [3, 0, 6, 5, 4, 0, 1, 2, 9, 1],
       [7, 6, 2, 1, 1, 8, 6, 8, 5, 4],
       [3, 4, 6, 0, 0, 9, 2, 7, 6, 0],
       [0, 9, 5, 8, 9, 8, 7, 3, 4, 8],
       [1, 3, 0, 6, 2, 0, 4, 1, 9, 6],
       [1, 4, 1, 6, 1, 1, 6, 2, 3, 9]])>

## Variables in TensorFlow

In [74]:
init_vals = tf.random.normal((1,5), 0, 1)
var = tf.Variable(init_vals)

print(var)

<tf.Variable 'Variable:0' shape=(1, 5) dtype=float32, numpy=
array([[1.2570537 , 0.5540329 , 0.45573652, 0.10030435, 1.9370241 ]],
      dtype=float32)>


In [19]:
tf.__version__

'2.10.1'

In [20]:
!nvidia-smi

Thu Aug 22 19:07:49 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.81                 Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   64C    P8             10W /  115W |     339MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [21]:
a = tf.constant(7)

In [22]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [23]:
a = tf.constant([1,2,3])

In [27]:
b=tf.expand_dims(a, 0)

In [28]:
b

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [29]:
b=tf.expand_dims(a, -2)
b

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [31]:
b=tf.expand_dims(a,1)
b

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [32]:
b=tf.expand_dims(a, -1)
b

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [33]:
b=tf.expand_dims(a, 0)
b

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [34]:
b=tf.expand_dims(a, -2)
b

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [35]:
b_var = tf.Variable(b)
b_var

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[1, 2, 3]])>

In [36]:
c_var = tf.Variable([[1.7, 2.2, 8], [1.09, 2.11, 2.65], [1.14, 2.664, 2.91]])
c_var

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1.7  , 2.2  , 8.   ],
       [1.09 , 2.11 , 2.65 ],
       [1.14 , 2.664, 2.91 ]], dtype=float32)>

In [2]:
initial_value = tf.random.normal((2,2))
a = tf.Variable(initial_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.51494783, -0.52726525],
       [-1.0259738 ,  1.4647484 ]], dtype=float32)>

In [3]:
new_value = tf.random.normal((2,2))
new_value

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.6144477 , -0.07983158],
       [-1.0530916 ,  0.45682594]], dtype=float32)>

In [4]:
a.assign(new_value)

for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [5]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.6144477 , -0.07983158],
       [-1.0530916 ,  0.45682594]], dtype=float32)>

In [8]:
added_value = tf.random.normal(shape=(2,2))

a.assign_add(added_value)

for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i, j] + added_value[i, j]
                

In [9]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.6374584 ,  1.1139536 ],
       [-0.22202581,  0.80641747]], dtype=float32)>

In [10]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

c = a + b

d = tf.square(c)

e = tf.exp(d)

In [11]:
print(c,d,e)

tf.Tensor(
[[-0.08599868 -0.5625997 ]
 [-1.5339816  -1.3930814 ]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0.00739577 0.31651846]
 [2.3530993  1.9406759 ]], shape=(2, 2), dtype=float32) tf.Tensor(
[[ 1.0074233  1.3723415]
 [10.518119   6.9634557]], shape=(2, 2), dtype=float32)


## Concatenation by tf.concatand making tensors by tf.constant

In [17]:
# Making a constant tensor A, that does not change:

A = tf.constant([ [3,2],
                  [5, 2] ])

# Making a variable tensor VA, which can change. Notice it's a variable.

VA = tf.Variable([[3,2], [5,2]])

# Making another tensor B

B = tf.constant([[9,5], [1,3]])

# Concatenate Columns

AB_concatenated = tf.concat(values=[A, B], axis=1)
print(f"Adding B's column to A: \n{AB_concatenated}")

# Concatenate Rows 

AB_concatenated = tf.concat(values = [A, B], axis=0)
print(f"\nAdding B's row to A:\n {AB_concatenated}")

Adding B's column to A: 
[[3 2 9 5]
 [5 2 1 3]]

Adding B's row to A:
 [[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [18]:
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 2],
       [9, 5],
       [1, 3]])>

## Making tensors using tf.zeros and tf.ones

In [22]:
# Making a tensor filled with zeros. shape = [rows, columns]

tensor = tf.zeros(shape=[3,4], dtype=tf.int32)

print(f"Tensor full of zeros having a shape of 3 rows and 4 columns: \n{tensor}")

# Making a tensor filled with zeros with data type of float32

tensor = tf.zeros(shape=[3,4], dtype = tf.float64)
print(f"\nTensor full of zeros having a shape of 3 rows and 4 columns: \n{tensor}")

Tensor full of zeros having a shape of 3 rows and 4 columns: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of zeros having a shape of 3 rows and 4 columns: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:

tensor = tf.ones(shape=[3,4], dtype = tf.float64)
print(f"\nTensor full of zeros having a shape of 3 rows and 4 columns: \n{tensor}")


Tensor full of zeros having a shape of 3 rows and 4 columns: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Making a tensor for reshapping

In [39]:
tensor = tf.constant([[3,2], [5, 2], [9,5], [1, 3]])

# Reshapping the tensor into another appropriate shape:

reshaped_tensor = tf.reshape(tensor, (1, -1))

print(f"Tensor before reshapping: \n{tensor}")
print(f"\nTensor after reshapping: \n{reshaped_tensor}")

Tensor before reshapping: 
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor after reshapping: 
[[3 2 5 2 9 5 1 3]]


## Type Casting in TensorFlow:

In [46]:
# Making a tensor

tensor = tf.constant([[3.1, 2.8], 
                     [5.2, 2.3], 
                     [9.7, 5.5], 
                     [1.1, 3.4]], 
                     dtype =tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

print(f"Tensor as float: \n{tensor}")
print(f"\nTensor as type-casted int: \n{tensor_as_int}")

Tensor as float: 
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor as type-casted int: 
[[3 2]
 [5 2]
 [9 5]
 [1 3]]
